# Generated by Django 3.1.1 on 2020-10-02 01:03

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=45)),
                ('CEP', models.CharField(max_length=20)),
                ('Rua', models.CharField(max_length=50)),
                ('Numero', models.SmallIntegerField()),
                ('Bairro', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=50)),
                ('Cidade', models.CharField(max_length=50)),
                ('Telefone1', models.CharField(max_length=20)),
                ('Telefone2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FaixaCor', models.CharField(default='Branco', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=45)),
                ('DataNascimento', models.DateField()),
                ('CPF', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('RGNumero', models.CharField(max_length=9)),
                ('RGOrgao', models.CharField(max_length=20)),
                ('RegistroCBJ', models.CharField(max_length=20)),
                ('CEP', models.CharField(max_length=20)),
                ('Rua', models.CharField(max_length=50)),
                ('Numero', models.SmallIntegerField()),
                ('Bairro', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=50)),
                ('Cidade', models.CharField(max_length=50)),
                ('Telefone1', models.CharField(max_length=20)),
                ('Telefone2', models.CharField(max_length=20)),
                ('Salario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Observacoes', models.TextField(max_length=50)),
                ('Academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academia')),
                ('Faixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faixa')),
            ],
        ),
        migrations.CreateModel(
            name='Filiado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=45)),
                ('DataNascimento', models.DateField()),
                ('CPF', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('RGNumero', models.CharField(max_length=9)),
                ('RGOrgao', models.CharField(max_length=20)),
                ('RegistroCBJ', models.CharField(max_length=20)),
                ('FaixaDataEntrega', models.DateTimeField(auto_now=True)),
                ('Rua', models.CharField(max_length=50)),
                ('CEP', models.CharField(max_length=20)),
                ('Numero', models.SmallIntegerField()),
                ('Bairro', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=50)),
                ('Cidade', models.CharField(max_length=50)),
                ('Telefone1', models.CharField(max_length=20)),
                ('Telefone2', models.CharField(max_length=20)),
                ('Observacoes', models.TextField(max_length=50)),
                ('UltimaAnuidade', models.DateField()),
                ('DataCadastro', models.DateField(auto_now=True)),
                ('Academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academia')),
                ('Faixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faixa')),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
            ],
        ),
    ]
