# Generated by Django 3.1.1 on 2020-09-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Endereco', models.IntegerField(max_length=5)),
                ('rua', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filiado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Filiado', models.IntegerField(max_length=5)),
                ('RegistroCBJ', models.CharField(max_length=20)),
                ('Nome', models.CharField(max_length=45)),
                ('CPF', models.CharField(max_length=11)),
                ('Categoria', models.CharField(max_length=20)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco')),
            ],
        ),
    ]
