# Generated by Django 3.1.1 on 2020-10-21 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='Professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
        migrations.AddField(
            model_name='professor',
            name='ProfessorAluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professor',
            name='UltimaAnuidade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
