# Generated by Django 3.1.1 on 2020-09-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiado',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='filiado',
            name='RegistroCBJ',
        ),
        migrations.RemoveField(
            model_name='filiado',
            name='endereco',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
