# Generated by Django 3.1.1 on 2020-10-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='Complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='Complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='Complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
