# Generated by Django 3.1.1 on 2020-10-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201021_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='RGNumero',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
