# Generated by Django 3.1.1 on 2020-10-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_academia_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='CNPJ',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
