# Generated by Django 3.1.1 on 2020-10-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academia_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='CNPJ',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
