# Generated by Django 3.1.1 on 2020-10-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201005_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faixa',
            name='FaixaCor',
            field=models.CharField(default='Branca', max_length=20),
        ),
        migrations.RemoveField(
            model_name='professor',
            name='Academia',
        ),
        migrations.AddField(
            model_name='professor',
            name='Academia',
            field=models.ManyToManyField(to='core.Academia'),
        ),
    ]
