# Generated by Django 3.1.1 on 2020-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201005_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.AlterField(
            model_name='professor',
            name='RegistroCBJ',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
